nve_water_flow_refresh:
  name: Refresh NVE Water Flow Data
  description: Manually refresh water flow data for all configured stations
  fields:
    station_name:
      name: Station Name
      description: Name of the station to refresh (optional, refreshes all if not specified)
      required: false
      example: "Gryta"
