
# Loads default set of integrations. Do not remove.
default_config:

logger:
  default: warning
  logs:
    custom_components.nve_water_flow: debug

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

