sildre_refresh:
  name: Refresh Sildre Data
  description: Manually refresh Sildre data for all configured stations
  fields:
    station_name:
      name: Station Name
      description: Name of the station to refresh (optional, refreshes all if not specified)
      required: false
      example: "Gryta"
